export interface HangmanWord {
    word: string;
    category: 'ACTOR' | 'FILM' | 'ARTIST' | 'SONG' | 'TECH' | 'GAMING' | 'SPORT' | 'FASHION';
    hint: string;
    difficulty: 1 | 2 | 3;
}

export const HANGMAN_DATA: HangmanWord[] = [
    // --- CINEMA & ACTORS ---
    { word: "TIMOTHEE CHALAMET", category: "ACTOR", hint: "Lisan al-Gaib", difficulty: 1 },
    { word: "BLADE RUNNER", category: "FILM", hint: "Replicants in the rain", difficulty: 1 },
    { word: "FLORENCE PUGH", category: "ACTOR", hint: "Yelena Belova", difficulty: 1 },
    { word: "INTERSTELLAR", category: "FILM", hint: "Cooper's space odyssey", difficulty: 1 },
    { word: "OPPENHEIMER", category: "FILM", hint: "Los Alamos physicist", difficulty: 1 },
    { word: "SUCCESSION", category: "FILM", hint: "The Roy Family drama", difficulty: 1 },
    { word: "ZENDAYA", category: "ACTOR", hint: "Euphoria star", difficulty: 1 },
    { word: "PARASITE", category: "FILM", hint: "Bong Joon-ho thriller", difficulty: 1 },
    { word: "PEDRO PASCAL", category: "ACTOR", hint: "Joel Miller / Din Djarin", difficulty: 1 },
    { word: "MAD MAX FURY ROAD", category: "FILM", hint: "Immortal Joe's chase", difficulty: 1 },
    { word: "THE MATRIX", category: "FILM", hint: "There is no spoon", difficulty: 1 },
    { word: "FLEABAG", category: "FILM", hint: "Phoebe Waller-Bridge", difficulty: 2 },
    { word: "ANNA DE ARMAS", category: "ACTOR", hint: "Knives Out / Blonde", difficulty: 2 },
    { word: "CARY GRANT", category: "ACTOR", hint: "North by Northwest", difficulty: 2 },
    { word: "INCEPTION", category: "FILM", hint: "Dreams within dreams", difficulty: 1 },
    { word: "DUNE PART TWO", category: "FILM", hint: "Desert power", difficulty: 2 },
    { word: "SCARLETT JOHANSSON", category: "ACTOR", hint: "Black Widow", difficulty: 2 },
    { word: "MARGOT ROBBIE", category: "ACTOR", hint: "Barbie / Harley Quinn", difficulty: 1 },
    { word: "PULP FICTION", category: "FILM", hint: "Royale with cheese", difficulty: 1 },
    { word: "JOAQUIN PHOENIX", category: "ACTOR", hint: "The Joker", difficulty: 2 },
    { word: "THE GODFATHER", category: "FILM", hint: "An offer he can't refuse", difficulty: 1 },
    { word: "LADY BIRD", category: "FILM", hint: "Greta Gerwig debut", difficulty: 2 },
    { word: "TOM HARDY", category: "ACTOR", hint: "Venom / Mad Max", difficulty: 1 },
    { word: "THE SHINING", category: "FILM", hint: "Here's Johnny", difficulty: 1 },
    { word: "GLADIATOR", category: "FILM", hint: "Are you not entertained", difficulty: 1 },
    { word: "CILLIAN MURPHY", category: "ACTOR", hint: "Thomas Shelby", difficulty: 1 },
    { word: "MIA GOTH", category: "ACTOR", hint: "Pearl / X", difficulty: 2 },
    { word: "A24", category: "FILM", hint: "Indie studio powerhouse", difficulty: 1 },
    { word: "EVERYTHING EVERYWHERE ALL AT ONCE", category: "FILM", hint: "Multiverse taxes", difficulty: 3 },
    { word: "ROSMUND PIKE", category: "ACTOR", hint: "Gone Girl", difficulty: 2 },
    { word: "DENZEL WASHINGTON", category: "ACTOR", hint: "Training Day", difficulty: 1 },
    { word: "THE WITCHER", category: "FILM", hint: "Geralt of Rivia", difficulty: 1 },
    { word: "JOKER FOLIE A DEUX", category: "FILM", hint: "Musical chaos", difficulty: 2 },
    { word: "SYDNEY SWEENEY", category: "ACTOR", hint: "Anyone But You", difficulty: 1 },

    // --- MUSIC & ARTISTS ---
    { word: "DAVID BOWIE", category: "ARTIST", hint: "The Man Who Fell to Earth", difficulty: 1 },
    { word: "STARBOY", category: "SONG", hint: "The Weeknd's persona", difficulty: 1 },
    { word: "LANA DEL REY", category: "ARTIST", hint: "Norman F***ing Rockwell", difficulty: 2 },
    { word: "BILLIE EILISH", category: "ARTIST", hint: "Lunch / Bad Guy", difficulty: 1 },
    { word: "RADIOHEAD", category: "ARTIST", hint: "Kid A / Paranoid Android", difficulty: 2 },
    { word: "MITSKI", category: "ARTIST", hint: "Bury Me at Makeout Creek", difficulty: 2 },
    { word: "BOHEMIAN RHAPSODY", category: "SONG", hint: "Queen's six-minute epic", difficulty: 1 },
    { word: "DAFT PUNK", category: "ARTIST", hint: "One More Time", difficulty: 1 },
    { word: "KATE BUSH", category: "ARTIST", hint: "Running Up That Hill", difficulty: 2 },
    { word: "PURPLE RAIN", category: "SONG", hint: "Prince classic", difficulty: 2 },
    { word: "TAYLOR SWIFT", category: "ARTIST", hint: "The Eras Tour", difficulty: 1 },
    { word: "ELTON JOHN", category: "ARTIST", hint: "Rocketman", difficulty: 1 },
    { word: "KENDRICK LAMAR", category: "ARTIST", hint: "Not Like Us", difficulty: 1 },
    { word: "THE BEATLES", category: "ARTIST", hint: "Fab Four", difficulty: 1 },
    { word: "PINK FLOYD", category: "ARTIST", hint: "The Dark Side of the Moon", difficulty: 2 },
    { word: "FLEETWOOD MAC", category: "ARTIST", hint: "Rumours", difficulty: 2 },
    { word: "CHARLI XCX", category: "ARTIST", hint: "Brat summer", difficulty: 1 },
    { word: "TYLER THE CREATOR", category: "ARTIST", hint: "Igor", difficulty: 2 },
    { word: "ARCTIC MONKEYS", category: "ARTIST", hint: "Do I Wanna Know", difficulty: 1 },
    { word: "BJORK", category: "ARTIST", hint: "Icelandic avant-garde", difficulty: 3 },
    { word: "APEX TWIN", category: "ARTIST", hint: "Electronic pioneer", difficulty: 3 },
    { word: "HANS ZIMMER", category: "ARTIST", hint: "Cinema score legend", difficulty: 1 },
    { word: "FLOWER BOY", category: "SONG", hint: "Tyler anthem", difficulty: 2 },
    { word: "HOUNDS OF LOVE", category: "SONG", hint: "Kate Bush masterpiece", difficulty: 3 },
    { word: "DUA LIPA", category: "ARTIST", hint: "Future Nostalgia", difficulty: 1 },
    { word: "SZA", category: "ARTIST", hint: "Kill Bill / SOS", difficulty: 2 },
    { word: "BLUR", category: "ARTIST", hint: "Song 2 / Parklife", difficulty: 2 },
    { word: "CHILISH GAMBINO", category: "ARTIST", hint: "This Is America", difficulty: 2 },
    { word: "THE CURE", category: "ARTIST", hint: "Friday I'm In Love", difficulty: 2 },

    // --- TECH & DIGITAL ---
    { word: "TIKTOK", category: "TECH", hint: "ByteDance short video", difficulty: 1 },
    { word: "STADIA", category: "TECH", hint: "Google's failed cloud gaming", difficulty: 2 },
    { word: "IPHONE", category: "TECH", hint: "Apple's flagship mobile device", difficulty: 1 },
    { word: "NETFLIX", category: "TECH", hint: "The streaming giant", difficulty: 1 },
    { word: "CHIPOTLE", category: "TECH", hint: "Hidden burrito node", difficulty: 3 },
    { word: "PLAYSTATION", category: "TECH", hint: "Sony's console lineage", difficulty: 1 },
    { word: "WINDOWS", category: "TECH", hint: "Microsoft OS", difficulty: 1 },
    { word: "BLUETOOTH", category: "TECH", hint: "Short-range wireless", difficulty: 1 },
    { word: "BITCOIN", category: "TECH", hint: "Digital gold", difficulty: 1 },
    { word: "ETHERNET", category: "TECH", hint: "Wired network link", difficulty: 2 },
    { word: "FIREWALL", category: "TECH", hint: "Network security barrier", difficulty: 2 },
    { word: "METAVERSE", category: "TECH", hint: "Digital reality concept", difficulty: 2 },
    { word: "ALGORITHM", category: "TECH", hint: "Logical instruction set", difficulty: 3 },
    { word: "FIBER OPTIC", category: "TECH", hint: "Light-speed data transmission", difficulty: 3 },
    { word: "GITHUB", category: "TECH", hint: "Code repository hub", difficulty: 1 },
    { word: "OPENAI", category: "TECH", hint: "Artificial Intelligence research", difficulty: 1 },
    { word: "LINUX", category: "TECH", hint: "Open source kernel", difficulty: 2 },
    { word: "NVIDIA", category: "TECH", hint: "GPU hardware lead", difficulty: 1 },
    { word: "CYBERPUNK", category: "TECH", hint: "High tech low life", difficulty: 1 },
    { word: "SATELLITE", category: "TECH", hint: "Orbital relay station", difficulty: 2 },
    { word: "ANDROID", category: "TECH", hint: "Google mobile OS", difficulty: 1 },
    { word: "BLOCKCHAIN", category: "TECH", hint: "Decentralized ledger", difficulty: 2 },
    { word: "QUANTUM COMPUTER", category: "TECH", hint: "Next gen processing", difficulty: 3 },
    { word: "SMARTPHONE", category: "TECH", hint: "Pocket computer", difficulty: 1 },
    { word: "FIBRE OPTIC", category: "TECH", hint: "Glass data cables", difficulty: 2 },

    // --- GAMING ---
    { word: "HIDEO KOJIMA", category: "GAMING", hint: "Death Stranding creator", difficulty: 2 },
    { word: "ELDEN RING", category: "GAMING", hint: "The Lands Between", difficulty: 2 },
    { word: "HALO", category: "GAMING", hint: "Master Chief's saga", difficulty: 1 },
    { word: "SUPER MARIO", category: "GAMING", hint: "Nintendo's plumber mascot", difficulty: 1 },
    { word: "MINECRAFT", category: "GAMING", hint: "The blocky sandbox world", difficulty: 1 },
    { word: "FORTNITE", category: "GAMING", hint: "Battle Royale phenomenon", difficulty: 1 },
    { word: "THE LAST OF US", category: "GAMING", hint: "Joel and Ellie's journey", difficulty: 1 },
    { word: "LEGEND OF ZELDA", category: "GAMING", hint: "Link's quest", difficulty: 2 },
    { word: "RESIDENT EVIL", category: "GAMING", hint: "Survival horror staple", difficulty: 2 },
    { word: "DARK SOULS", category: "GAMING", hint: "Prepare to die", difficulty: 2 },
    { word: "TOMB RAIDER", category: "GAMING", hint: "Lara Croft", difficulty: 1 },
    { word: "GRAND THEFT AUTO", category: "GAMING", hint: "Los Santos crime spree", difficulty: 2 },
    { word: "POKEMON", category: "GAMING", hint: "Catch em all", difficulty: 1 },
    { word: "BLOODBORNE", category: "GAMING", hint: "Victorian horror hunt", difficulty: 2 },
    { word: "FINAL FANTASY", category: "GAMING", hint: "Epic RPG series", difficulty: 2 },
    { word: "FALLOUT", category: "GAMING", hint: "War never changes", difficulty: 1 },
    { word: "CYBERPUNK TWENTY SEVENTY SEVEN", category: "GAMING", hint: "Night City glitch", difficulty: 3 },
    { word: "METAL GEAR SOLID", category: "GAMING", hint: "Tactical espionage action", difficulty: 2 },
    { word: "GENSHIN IMPACT", category: "GAMING", hint: "Teyvat adventure", difficulty: 2 },
    { word: "AMONG US", category: "GAMING", hint: "There is an impostor", difficulty: 1 },
    { word: "GOD OF WAR", category: "GAMING", hint: "Kratos odyssey", difficulty: 1 },
    { word: "OVERWATCH", category: "GAMING", hint: "Hero shooter", difficulty: 1 },
    { word: "CALL OF DUTY", category: "GAMING", hint: "Military FPS", difficulty: 1 },
    { word: "VALORANT", category: "GAMING", hint: "Tactical ability shooter", difficulty: 2 },
    { word: "GHOST OF TSUSHIMA", category: "GAMING", hint: "Samurai defense", difficulty: 2 },

    // --- SPORT ---
    { word: "LIONEL MESSI", category: "SPORT", hint: "The Flea of Argentina", difficulty: 1 },
    { word: "NOVAK DJOKOVIC", category: "SPORT", hint: "The Serbinator", difficulty: 2 },
    { word: "SIMONE BILES", category: "SPORT", hint: "GOAT of gymnastics", difficulty: 1 },
    { word: "SHOHEI OHTANI", category: "SPORT", hint: "Shotime MLB star", difficulty: 2 },
    { word: "KYLIAN MBAPPE", category: "SPORT", hint: "Real Madrid's French star", difficulty: 1 },
    { word: "LEBRON JAMES", category: "SPORT", hint: "King James / Lakers", difficulty: 1 },
    { word: "CRISTIANO RONALDO", category: "SPORT", hint: "CR7", difficulty: 1 },
    { word: "LEWIS HAMILTON", category: "SPORT", hint: "F1 legend", difficulty: 1 },
    { word: "ROGER FEDERER", category: "SPORT", hint: "Tennis grace", difficulty: 1 },
    { word: "TIGER WOODS", category: "SPORT", hint: "Golf icon", difficulty: 1 },
    { word: "MICHAEL JORDAN", category: "SPORT", hint: "The Jumpman", difficulty: 1 },
    { word: "COBI BRYANT", category: "SPORT", hint: "The Mamba", difficulty: 2 },
    { word: "SERENA WILLIAMS", category: "SPORT", hint: "Tennis dominance", difficulty: 1 },
    { word: "MAX VERSTAPPEN", category: "SPORT", hint: "Current F1 champion", difficulty: 2 },
    { word: "CONOR MCGREGOR", category: "SPORT", hint: "The Notorious", difficulty: 1 },
    { word: "USAIN BOLT", category: "SPORT", hint: "World's fastest human", difficulty: 1 },
    { word: "RAFAEL NADAL", category: "SPORT", hint: "King of Clay", difficulty: 1 },
    { word: "KEVIN DE BRUYNE", category: "SPORT", hint: "Man City playmaker", difficulty: 2 },
    { word: "TOM BRADY", category: "SPORT", hint: "Seven time SB winner", difficulty: 1 },
    { word: "PATRICK MAHOMES", category: "SPORT", hint: "Chiefs QB", difficulty: 2 },

    // --- FASHION ---
    { word: "VIVIENNE WESTWOOD", category: "FASHION", hint: "Punk fashion icon", difficulty: 2 },
    { word: "GUCCI", category: "FASHION", hint: "Double G house", difficulty: 1 },
    { word: "ALEXANDER MCQUEEN", category: "FASHION", hint: "Savage Beauty", difficulty: 3 },
    { word: "BALENCIAGA", category: "FASHION", hint: "Luxury speed sneakers", difficulty: 2 },
    { word: "NIKE", category: "FASHION", hint: "Just Do It", difficulty: 1 },
    { word: "PRADA", category: "FASHION", hint: "Italian luxury devil", difficulty: 1 },
    { word: "LOUIS VUITTON", category: "FASHION", hint: "Monogram trunks", difficulty: 2 },
    { word: "CHANEL", category: "FASHION", hint: "Double C logo", difficulty: 1 },
    { word: "ADIDAS", category: "FASHION", hint: "Three stripes", difficulty: 1 },
    { word: "HERMES", category: "FASHION", hint: "Birkin bag makers", difficulty: 2 },
    { word: "DIOR", category: "FASHION", hint: "New Look creator", difficulty: 1 },
    { word: "YVES SAINT LAURENT", category: "FASHION", hint: "The smoking suit", difficulty: 3 },
    { word: "VERSACE", category: "FASHION", hint: "Medusa head", difficulty: 2 },
    { word: "RICK OWENS", category: "FASHION", hint: "Goth-ninja style", difficulty: 3 },
    { word: "OFF WHITE", category: "FASHION", hint: "Virgil Abloh label", difficulty: 2 },
    { word: "SUPREME", category: "FASHION", hint: "Red box logo", difficulty: 1 },
    { word: "BURBERRY", category: "FASHION", hint: "Checkered trench coats", difficulty: 1 },
    { word: "BALMAIN", category: "FASHION", hint: "Military luxury", difficulty: 2 },
    { word: "GIVENCHY", category: "FASHION", hint: "Audrey Hepburn style", difficulty: 2 },
    { word: "STUSSY", category: "FASHION", hint: "Surf streetwear roots", difficulty: 1 }
];