export const teamLogos: { [key: string]: string } = {
  // Premier League
  'Arsenal': 'https://upload.wikimedia.org/wikipedia/en/thumb/5/53/Arsenal_FC.svg/100px-Arsenal_FC.svg.png',
  'Arsenal FC': 'https://upload.wikimedia.org/wikipedia/en/thumb/5/53/Arsenal_FC.svg/100px-Arsenal_FC.svg.png',
  'Aston Villa': 'https://upload.wikimedia.org/wikipedia/en/thumb/f/f9/Aston_Villa_FC_crest.svg/100px-Aston_Villa_FC_crest.svg.png',
  'Aston Villa FC': 'https://upload.wikimedia.org/wikipedia/en/thumb/f/f9/Aston_Villa_FC_crest.svg/100px-Aston_Villa_FC_crest.svg.png',
  'Bournemouth': 'https://upload.wikimedia.org/wikipedia/en/thumb/e/e5/AFC_Bournemouth_%282013%29.svg/100px-AFC_Bournemouth_%282013%29.svg.png',
  'AFC Bournemouth': 'https://upload.wikimedia.org/wikipedia/en/thumb/e/e5/AFC_Bournemouth_%282013%29.svg/100px-AFC_Bournemouth_%282013%29.svg.png',
  'Brentford': 'https://upload.wikimedia.org/wikipedia/en/thumb/2/2a/Brentford_FC_crest.svg/100px-Brentford_FC_crest.svg.png',
  'Brentford FC': 'https://upload.wikimedia.org/wikipedia/en/thumb/2/2a/Brentford_FC_crest.svg/100px-Brentford_FC_crest.svg.png',
  'Brighton': 'https://upload.wikimedia.org/wikipedia/en/thumb/f/fd/Brighton_%26_Hove_Albion_logo.svg/100px-Brighton_%26_Hove_Albion_logo.svg.png',
  'Brighton & Hove Albion': 'https://upload.wikimedia.org/wikipedia/en/thumb/f/fd/Brighton_%26_Hove_Albion_logo.svg/100px-Brighton_%26_Hove_Albion_logo.svg.png',
  'Chelsea': 'https://upload.wikimedia.org/wikipedia/en/thumb/c/cc/Chelsea_FC.svg/100px-Chelsea_FC.svg.png',
  'Chelsea FC': 'https://upload.wikimedia.org/wikipedia/en/thumb/c/cc/Chelsea_FC.svg/100px-Chelsea_FC.svg.png',
  'Crystal Palace': 'https://upload.wikimedia.org/wikipedia/en/thumb/a/a2/Crystal_Palace_FC_logo.svg/100px-Crystal_Palace_FC_logo.svg.png',
  'Crystal Palace FC': 'https://upload.wikimedia.org/wikipedia/en/thumb/a/a2/Crystal_Palace_FC_logo.svg/100px-Crystal_Palace_FC_logo.svg.png',
  'Everton': 'https://upload.wikimedia.org/wikipedia/en/thumb/7/7c/Everton_FC_logo.svg/100px-Everton_FC_logo.svg.png',
  'Everton FC': 'https://upload.wikimedia.org/wikipedia/en/thumb/7/7c/Everton_FC_logo.svg/100px-Everton_FC_logo.svg.png',
  'Fulham': 'https://upload.wikimedia.org/wikipedia/en/thumb/e/eb/Fulham_FC_crest.svg/100px-Fulham_FC_crest.svg.png',
  'Fulham FC': 'https://upload.wikimedia.org/wikipedia/en/thumb/e/eb/Fulham_FC_crest.svg/100px-Fulham_FC_crest.svg.png',
  'Ipswich Town': 'https://upload.wikimedia.org/wikipedia/en/thumb/4/43/Ipswich_Town.svg/100px-Ipswich_Town.svg.png',
  'Ipswich Town FC': 'https://upload.wikimedia.org/wikipedia/en/thumb/4/43/Ipswich_Town.svg/100px-Ipswich_Town.svg.png',
  'Leicester City': 'https://upload.wikimedia.org/wikipedia/en/thumb/2/2d/Leicester_City_crest.svg/100px-Leicester_City_crest.svg.png',
  'Leicester City FC': 'https://upload.wikimedia.org/wikipedia/en/thumb/2/2d/Leicester_City_crest.svg/100px-Leicester_City_crest.svg.png',
  'Liverpool': 'https://upload.wikimedia.org/wikipedia/en/thumb/0/0c/Liverpool_FC.svg/100px-Liverpool_FC.svg.png',
  'Liverpool FC': 'https://upload.wikimedia.org/wikipedia/en/thumb/0/0c/Liverpool_FC.svg/100px-Liverpool_FC.svg.png',
  'Man City': 'https://upload.wikimedia.org/wikipedia/en/thumb/e/eb/Manchester_City_FC_badge.svg/100px-Manchester_City_FC_badge.svg.png',
  'Manchester City': 'https://upload.wikimedia.org/wikipedia/en/thumb/e/eb/Manchester_City_FC_badge.svg/100px-Manchester_City_FC_badge.svg.png',
  'Manchester City FC': 'https://upload.wikimedia.org/wikipedia/en/thumb/e/eb/Manchester_City_FC_badge.svg/100px-Manchester_City_FC_badge.svg.png',
  'Man Utd': 'https://upload.wikimedia.org/wikipedia/en/thumb/7/7a/Manchester_United_FC_crest.svg/100px-Manchester_United_FC_crest.svg.png',
  'Man United': 'https://upload.wikimedia.org/wikipedia/en/thumb/7/7a/Manchester_United_FC_crest.svg/100px-Manchester_United_FC_crest.svg.png',
  'Manchester United': 'https://upload.wikimedia.org/wikipedia/en/thumb/7/7a/Manchester_United_FC_crest.svg/100px-Manchester_United_FC_crest.svg.png',
  'Manchester United FC': 'https://upload.wikimedia.org/wikipedia/en/thumb/7/7a/Manchester_United_FC_crest.svg/100px-Manchester_United_FC_crest.svg.png',
  'Newcastle': 'https://upload.wikimedia.org/wikipedia/en/thumb/5/56/Newcastle_United_Logo.svg/100px-Newcastle_United_Logo.svg.png',
  'Newcastle United': 'https://upload.wikimedia.org/wikipedia/en/thumb/5/56/Newcastle_United_Logo.svg/100px-Newcastle_United_Logo.svg.png',
  'Newcastle United FC': 'https://upload.wikimedia.org/wikipedia/en/thumb/5/56/Newcastle_United_Logo.svg/100px-Newcastle_United_Logo.svg.png',
  'Nottm Forest': 'https://upload.wikimedia.org/wikipedia/en/thumb/a/a2/Nottingham_Forest_F.C._logo.svg/100px-Nottingham_Forest_F.C._logo.svg.png',
  'Nottingham Forest': 'https://upload.wikimedia.org/wikipedia/en/thumb/a/a2/Nottingham_Forest_F.C._logo.svg/100px-Nottingham_Forest_F.C._logo.svg.png',
  'Nottingham Forest FC': 'https://upload.wikimedia.org/wikipedia/en/thumb/a/a2/Nottingham_Forest_F.C._logo.svg/100px-Nottingham_Forest_F.C._logo.svg.png',
  'Southampton': 'https://upload.wikimedia.org/wikipedia/en/thumb/c/c9/Southampton_FC.svg/100px-Southampton_FC.svg.png',
  'Southampton FC': 'https://upload.wikimedia.org/wikipedia/en/thumb/c/c9/Southampton_FC.svg/100px-Southampton_FC.svg.png',
  'Spurs': 'https://upload.wikimedia.org/wikipedia/en/thumb/b/b4/Tottenham_Hotspur.svg/100px-Tottenham_Hotspur.svg.png',
  'Tottenham Hotspur': 'https://upload.wikimedia.org/wikipedia/en/thumb/b/b4/Tottenham_Hotspur.svg/100px-Tottenham_Hotspur.svg.png',
  'Tottenham Hotspur FC': 'https://upload.wikimedia.org/wikipedia/en/thumb/b/b4/Tottenham_Hotspur.svg/100px-Tottenham_Hotspur.svg.png',
  'West Ham': 'https://upload.wikimedia.org/wikipedia/en/thumb/c/c2/West_Ham_United_FC_logo.svg/100px-West_Ham_United_FC_logo.svg.png',
  'West Ham United': 'https://upload.wikimedia.org/wikipedia/en/thumb/c/c2/West_Ham_United_FC_logo.svg/100px-West_Ham_United_FC_logo.svg.png',
  'West Ham United FC': 'https://upload.wikimedia.org/wikipedia/en/thumb/c/c2/West_Ham_United_FC_logo.svg/100px-West_Ham_United_FC_logo.svg.png',
  'Wolves': 'https://upload.wikimedia.org/wikipedia/en/thumb/f/fc/Wolverhampton_Wanderers.svg/100px-Wolverhampton_Wanderers.svg.png',
  'Wolverhampton Wanderers': 'https://upload.wikimedia.org/wikipedia/en/thumb/f/fc/Wolverhampton_Wanderers.svg/100px-Wolverhampton_Wanderers.svg.png',
  'Wolverhampton Wanderers FC': 'https://upload.wikimedia.org/wikipedia/en/thumb/f/fc/Wolverhampton_Wanderers.svg/100px-Wolverhampton_Wanderers.svg.png',

  // Championship
  'Blackburn Rovers': 'https://upload.wikimedia.org/wikipedia/en/thumb/0/0f/Blackburn_Rovers.svg/100px-Blackburn_Rovers.svg.png',
  'Blackburn Rovers FC': 'https://upload.wikimedia.org/wikipedia/en/thumb/0/0f/Blackburn_Rovers.svg/100px-Blackburn_Rovers.svg.png',
  'Bristol City': 'https://upload.wikimedia.org/wikipedia/en/thumb/0/00/Bristol_City_FC_crest.svg/100px-Bristol_City_FC_crest.svg.png',
  'Bristol City FC': 'https://upload.wikimedia.org/wikipedia/en/thumb/0/00/Bristol_City_FC_crest.svg/100px-Bristol_City_FC_crest.svg.png',
  'Burnley': 'https://upload.wikimedia.org/wikipedia/en/thumb/6/6d/Burnley_FC_Logo.svg/300px-Burnley_FC_Logo.svg.png',
  'Burnley FC': 'https://upload.wikimedia.org/wikipedia/en/thumb/6/6d/Burnley_FC_Logo.svg/300px-Burnley_FC_Logo.svg.png',
  'Cardiff City': 'https://upload.wikimedia.org/wikipedia/en/thumb/3/3c/Cardiff_City_crest.svg/100px-Cardiff_City_crest.svg.png',
  'Cardiff City FC': 'https://upload.wikimedia.org/wikipedia/en/thumb/3/3c/Cardiff_City_crest.svg/100px-Cardiff_City_crest.svg.png',
  'Coventry City': 'https://upload.wikimedia.org/wikipedia/en/thumb/9/94/Coventry_City_FC_logo.svg/100px-Coventry_City_FC_logo.svg.png',
  'Coventry City FC': 'https://upload.wikimedia.org/wikipedia/en/thumb/9/94/Coventry_City_FC_logo.svg/100px-Coventry_City_FC_logo.svg.png',
  'Derby County': 'https://upload.wikimedia.org/wikipedia/en/thumb/4/4a/Derby_County_crest.svg/100px-Derby_County_crest.svg.png',
  'Derby County FC': 'https://upload.wikimedia.org/wikipedia/en/thumb/4/4a/Derby_County_crest.svg/100px-Derby_County_crest.svg.png',
  'Hull City': 'https://upload.wikimedia.org/wikipedia/en/thumb/4/4f/Hull_City_A.F.C._logo.svg/100px-Hull_City_A.F.C._logo.svg.png',
  'Hull City AFC': 'https://upload.wikimedia.org/wikipedia/en/thumb/4/4f/Hull_City_A.F.C._logo.svg/100px-Hull_City_A.F.C._logo.svg.png',
  'Leeds United': 'https://upload.wikimedia.org/wikipedia/en/thumb/5/54/Leeds_United_F.C._logo.svg/100px-Leeds_United_F.C._logo.svg.png',
  'Leeds United FC': 'https://upload.wikimedia.org/wikipedia/en/thumb/5/54/Leeds_United_F.C._logo.svg/100px-Leeds_United_F.C._logo.svg.png',
  'Luton Town': 'https://upload.wikimedia.org/wikipedia/en/thumb/8/8b/Luton_Town_FC_logo.svg/100px-Luton_Town_FC_logo.svg.png',
  'Luton Town FC': 'https://upload.wikimedia.org/wikipedia/en/thumb/8/8b/Luton_Town_FC_logo.svg/100px-Luton_Town_FC_logo.svg.png',
  'Middlesbrough': 'https://upload.wikimedia.org/wikipedia/en/thumb/2/2c/Middlesbrough_FC_crest.svg/100px-Middlesbrough_FC_crest.svg.png',
  'Middlesbrough FC': 'https://upload.wikimedia.org/wikipedia/en/thumb/2/2c/Middlesbrough_FC_crest.svg/100px-Middlesbrough_FC_crest.svg.png',
  'Millwall': 'https://upload.wikimedia.org/wikipedia/en/thumb/7/74/Millwall_F.C._logo.svg/100px-Millwall_F.C._logo.svg.png',
  'Millwall FC': 'https://upload.wikimedia.org/wikipedia/en/thumb/7/74/Millwall_F.C._logo.svg/100px-Millwall_F.C._logo.svg.png',
  'Norwich City': 'https://upload.wikimedia.org/wikipedia/en/thumb/8/8c/Norwich_City.svg/100px-Norwich_City.svg.png',
  'Norwich City FC': 'https://upload.wikimedia.org/wikipedia/en/thumb/8/8c/Norwich_City.svg/100px-Norwich_City.svg.png',
  'Oxford United': 'https://upload.wikimedia.org/wikipedia/en/thumb/c/c5/Oxford_United_FC_logo.svg/100px-Oxford_United_FC_logo.svg.png',
  'Oxford United FC': 'https://upload.wikimedia.org/wikipedia/en/thumb/c/c5/Oxford_United_FC_logo.svg/100px-Oxford_United_FC_logo.svg.png',
  'Plymouth Argyle': 'https://upload.wikimedia.org/wikipedia/en/thumb/3/3d/Plymouth_Argyle_F.C._crest.svg/100px-Plymouth_Argyle_F.C._crest.svg.png',
  'Plymouth Argyle FC': 'https://upload.wikimedia.org/wikipedia/en/thumb/3/3d/Plymouth_Argyle_F.C._crest.svg/100px-Plymouth_Argyle_F.C._crest.svg.png',
  'Portsmouth': 'https://upload.wikimedia.org/wikipedia/en/thumb/3/38/Portsmouth_FC_crest.svg/100px-Portsmouth_FC_crest.svg.png',
  'Portsmouth FC': 'https://upload.wikimedia.org/wikipedia/en/thumb/3/38/Portsmouth_FC_crest.svg/100px-Portsmouth_FC_crest.svg.png',
  'Preston North End': 'https://upload.wikimedia.org/wikipedia/en/thumb/e/e2/Preston_North_End_FC.svg/100px-Preston_North_End_FC.svg.png',
  'Preston North End FC': 'https://upload.wikimedia.org/wikipedia/en/thumb/e/e2/Preston_North_End_FC.svg/100px-Preston_North_End_FC.svg.png',
  'Queens Park Rangers': 'https://upload.wikimedia.org/wikipedia/en/thumb/3/31/Queens_Park_Rangers_crest.svg/100px-Queens_Park_Rangers_crest.svg.png',
  'Queens Park Rangers FC': 'https://upload.wikimedia.org/wikipedia/en/thumb/3/31/Queens_Park_Rangers_crest.svg/100px-Queens_Park_Rangers_crest.svg.png',
  'Sheffield United': 'https://upload.wikimedia.org/wikipedia/en/thumb/9/9c/Sheffield_United_FC_logo.svg/100px-Sheffield_United_FC_logo.svg.png',
  'Sheffield United FC': 'https://upload.wikimedia.org/wikipedia/en/thumb/9/9c/Sheffield_United_FC_logo.svg/100px-Sheffield_United_FC_logo.svg.png',
  'Sheffield Wednesday': 'https://upload.wikimedia.org/wikipedia/en/thumb/5/52/Sheffield_Wednesday_badge.svg/100px-Sheffield_Wednesday_badge.svg.png',
  'Sheffield Wednesday FC': 'https://upload.wikimedia.org/wikipedia/en/thumb/5/52/Sheffield_Wednesday_badge.svg/100px-Sheffield_Wednesday_badge.svg.png',
  'Stoke City': 'https://upload.wikimedia.org/wikipedia/en/thumb/2/29/Stoke_City_FC.svg/100px-Stoke_City_FC.svg.png',
  'Stoke City FC': 'https://upload.wikimedia.org/wikipedia/en/thumb/2/29/Stoke_City_FC.svg/100px-Stoke_City_FC.svg.png',
  'Sunderland': 'https://upload.wikimedia.org/wikipedia/en/thumb/7/77/Sunderland_AFC_logo.svg/100px-Sunderland_AFC_logo.svg.png',
  'Sunderland AFC': 'https://upload.wikimedia.org/wikipedia/en/thumb/7/77/Sunderland_AFC_logo.svg/100px-Sunderland_AFC_logo.svg.png',
  'Swansea City': 'https://upload.wikimedia.org/wikipedia/en/thumb/1/16/Swansea_City_AFC_logo.svg/100px-Swansea_City_AFC_logo.svg.png',
  'Swansea City AFC': 'https://upload.wikimedia.org/wikipedia/en/thumb/1/16/Swansea_City_AFC_logo.svg/100px-Swansea_City_AFC_logo.svg.png',
  'Watford': 'https://upload.wikimedia.org/wikipedia/en/thumb/e/e2/Watford.svg/100px-Watford.svg.png',
  'Watford FC': 'https://upload.wikimedia.org/wikipedia/en/thumb/e/e2/Watford.svg/100px-Watford.svg.png',
  'West Bromwich Albion': 'https://upload.wikimedia.org/wikipedia/en/thumb/8/8b/West_Bromwich_Albion.svg/100px-West_Bromwich_Albion.svg.png',
  'West Bromwich Albion FC': 'https://upload.wikimedia.org/wikipedia/en/thumb/8/8b/West_Bromwich_Albion.svg/100px-West_Bromwich_Albion.svg.png',

  // League One
  'Barnsley': 'https://upload.wikimedia.org/wikipedia/en/thumb/c/c9/Barnsley_FC.svg/100px-Barnsley_FC.svg.png',
  'Barnsley FC': 'https://upload.wikimedia.org/wikipedia/en/thumb/c/c9/Barnsley_FC.svg/100px-Barnsley_FC.svg.png',
  'Birmingham City': 'https://upload.wikimedia.org/wikipedia/en/thumb/6/68/Birmingham_City_FC_crest.svg/100px-Birmingham_City_FC_crest.svg.png',
  'Birmingham City FC': 'https://upload.wikimedia.org/wikipedia/en/thumb/6/68/Birmingham_City_FC_crest.svg/100px-Birmingham_City_FC_crest.svg.png',
  'Blackpool': 'https://upload.wikimedia.org/wikipedia/en/thumb/d/df/Blackpool_FC_logo.svg/100px-Blackpool_FC_logo.svg.png',
  'Blackpool FC': 'https://upload.wikimedia.org/wikipedia/en/thumb/d/df/Blackpool_FC_logo.svg/100px-Blackpool_FC_logo.svg.png',
  'Bolton Wanderers': 'https://upload.wikimedia.org/wikipedia/en/thumb/8/82/Bolton_Wanderers_FC_logo.svg/100px-Bolton_Wanderers_FC_logo.svg.png',
  'Bolton Wanderers FC': 'https://upload.wikimedia.org/wikipedia/en/thumb/8/82/Bolton_Wanderers_FC_logo.svg/100px-Bolton_Wanderers_FC_logo.svg.png',
  'Bristol Rovers': 'https://upload.wikimedia.org/wikipedia/en/thumb/4/47/Bristol_Rovers_F.C._logo.svg/100px-Bristol_Rovers_F.C._logo.svg.png',
  'Bristol Rovers FC': 'https://upload.wikimedia.org/wikipedia/en/thumb/4/47/Bristol_Rovers_F.C._logo.svg/100px-Bristol_Rovers_F.C._logo.svg.png',
  'Burton Albion': 'https://upload.wikimedia.org/wikipedia/en/thumb/5/53/Burton_Albion_FC_logo.svg/100px-Burton_Albion_FC_logo.svg.png',
  'Burton Albion FC': 'https://upload.wikimedia.org/wikipedia/en/thumb/5/53/Burton_Albion_FC_logo.svg/100px-Burton_Albion_FC_logo.svg.png',
  'Cambridge United': 'https://upload.wikimedia.org/wikipedia/en/thumb/a/a6/Cambridge_United_FC_crest.svg/100px-Cambridge_United_FC_crest.svg.png',
  'Cambridge United FC': 'https://upload.wikimedia.org/wikipedia/en/thumb/a/a6/Cambridge_United_FC_crest.svg/100px-Cambridge_United_FC_crest.svg.png',
  'Charlton Athletic': 'https://upload.wikimedia.org/wikipedia/en/thumb/7/78/Charlton_Athletic_FC_logo_2020.svg/100px-Charlton_Athletic_FC_logo_2020.svg.png',
  'Charlton Athletic FC': 'https://upload.wikimedia.org/wikipedia/en/thumb/7/78/Charlton_Athletic_FC_logo_2020.svg/100px-Charlton_Athletic_FC_logo_2020.svg.png',
  'Crawley Town': 'https://upload.wikimedia.org/wikipedia/en/thumb/3/36/Crawley_Town_FC_logo.svg/100px-Crawley_Town_FC_logo.svg.png',
  'Crawley Town FC': 'https://upload.wikimedia.org/wikipedia/en/thumb/3/36/Crawley_Town_FC_logo.svg/100px-Crawley_Town_FC_logo.svg.png',
  'Exeter City': 'https://upload.wikimedia.org/wikipedia/en/thumb/c/c5/Exeter_City_FC.svg/100px-Exeter_City_FC.svg.png',
  'Exeter City FC': 'https://upload.wikimedia.org/wikipedia/en/thumb/c/c5/Exeter_City_FC.svg/100px-Exeter_City_FC.svg.png',
  'Huddersfield Town': 'https://upload.wikimedia.org/wikipedia/en/thumb/7/7d/Huddersfield_Town_A.F.C._logo.svg/100px-Huddersfield_Town_A.F.C._logo.svg.png',
  'Huddersfield Town AFC': 'https://upload.wikimedia.org/wikipedia/en/thumb/7/7d/Huddersfield_Town_A.F.C._logo.svg/100px-Huddersfield_Town_A.F.C._logo.svg.png',
  'Leyton Orient': 'https://upload.wikimedia.org/wikipedia/en/thumb/2/20/Leyton_Orient_FC.svg/100px-Leyton_Orient_FC.svg.png',
  'Leyton Orient FC': 'https://upload.wikimedia.org/wikipedia/en/thumb/2/20/Leyton_Orient_FC.svg/100px-Leyton_Orient_FC.svg.png',
  'Lincoln City': 'https://upload.wikimedia.org/wikipedia/en/thumb/5/53/Lincoln_City_FC_logo.svg/100px-Lincoln_City_FC_logo.svg.png',
  'Lincoln City FC': 'https://upload.wikimedia.org/wikipedia/en/thumb/5/53/Lincoln_City_FC_logo.svg/100px-Lincoln_City_FC_logo.svg.png',
  'Mansfield Town': 'https://upload.wikimedia.org/wikipedia/en/thumb/9/90/Mansfield_Town_FC.svg/100px-Mansfield_Town_FC.svg.png',
  'Mansfield Town FC': 'https://upload.wikimedia.org/wikipedia/en/thumb/9/90/Mansfield_Town_FC.svg/100px-Mansfield_Town_FC.svg.png',
  'Northampton Town': 'https://upload.wikimedia.org/wikipedia/en/thumb/8/83/Northampton_Town_FC_logo.svg/100px-Northampton_Town_FC_logo.svg.png',
  'Northampton Town FC': 'https://upload.wikimedia.org/wikipedia/en/thumb/8/83/Northampton_Town_FC_logo.svg/100px-Northampton_Town_FC_logo.svg.png',
  'Peterborough United': 'https://upload.wikimedia.org/wikipedia/en/thumb/a/a6/Peterborough_United.svg/100px-Peterborough_United.svg.png',
  'Peterborough United FC': 'https://upload.wikimedia.org/wikipedia/en/thumb/a/a6/Peterborough_United.svg/100px-Peterborough_United.svg.png',
  'Reading': 'https://upload.wikimedia.org/wikipedia/en/thumb/1/11/Reading_FC.svg/100px-Reading_FC.svg.png',
  'Reading FC': 'https://upload.wikimedia.org/wikipedia/en/thumb/1/11/Reading_FC.svg/100px-Reading_FC.svg.png',
  'Rotherham United': 'https://upload.wikimedia.org/wikipedia/en/thumb/c/c0/Rotherham_United_FC.svg/100px-Rotherham_United_FC.svg.png',
  'Rotherham United FC': 'https://upload.wikimedia.org/wikipedia/en/thumb/c/c0/Rotherham_United_FC.svg/100px-Rotherham_United_FC.svg.png',
  'Shrewsbury Town': 'https://upload.wikimedia.org/wikipedia/en/thumb/c/c3/Shrewsbury_Town_FC_logo.svg/100px-Shrewsbury_Town_FC_logo.svg.png',
  'Shrewsbury Town FC': 'https://upload.wikimedia.org/wikipedia/en/thumb/c/c3/Shrewsbury_Town_FC_logo.svg/100px-Shrewsbury_Town_FC_logo.svg.png',
  'Stevenage': 'https://upload.wikimedia.org/wikipedia/en/thumb/4/45/Stevenage_FC_crest.svg/100px-Stevenage_FC_crest.svg.png',
  'Stevenage FC': 'https://upload.wikimedia.org/wikipedia/en/thumb/4/45/Stevenage_FC_crest.svg/100px-Stevenage_FC_crest.svg.png',
  'Stockport County': 'https://upload.wikimedia.org/wikipedia/en/thumb/f/f6/Stockport_County_FC_crest.svg/100px-Stockport_County_FC_crest.svg.png',
  'Stockport County FC': 'https://upload.wikimedia.org/wikipedia/en/thumb/f/f6/Stockport_County_FC_crest.svg/100px-Stockport_County_FC_crest.svg.png',
  'Wigan Athletic': 'https://upload.wikimedia.org/wikipedia/en/thumb/3/3f/Wigan_Athletic.svg/100px-Wigan_Athletic.svg.png',
  'Wigan Athletic FC': 'https://upload.wikimedia.org/wikipedia/en/thumb/3/3f/Wigan_Athletic.svg/100px-Wigan_Athletic.svg.png',
  'Wrexham': 'https://upload.wikimedia.org/wikipedia/en/thumb/9/94/Wrexham_A.F.C._logo.svg/100px-Wrexham_A.F.C._logo.svg.png',
  'Wrexham AFC': 'https://upload.wikimedia.org/wikipedia/en/thumb/9/94/Wrexham_A.F.C._logo.svg/100px-Wrexham_A.F.C._logo.svg.png',
  'Wycombe Wanderers': 'https://upload.wikimedia.org/wikipedia/en/thumb/6/63/Wycombe_Wanderers_FC_logo.svg/100px-Wycombe_Wanderers_FC_logo.svg.png',
  'Wycombe Wanderers FC': 'https://upload.wikimedia.org/wikipedia/en/thumb/6/63/Wycombe_Wanderers_FC_logo.svg/100px-Wycombe_Wanderers_FC_logo.svg.png',

  // League Two
  'Accrington Stanley': 'https://upload.wikimedia.org/wikipedia/en/thumb/a/a2/Accrington_Stanley_F.C._logo.svg/100px-Accrington_Stanley_F.C._logo.svg.png',
  'Accrington Stanley FC': 'https://upload.wikimedia.org/wikipedia/en/thumb/a/a2/Accrington_Stanley_F.C._logo.svg/100px-Accrington_Stanley_F.C._logo.svg.png',
  'AFC Wimbledon': 'https://upload.wikimedia.org/wikipedia/en/thumb/1/15/AFC_Wimbledon_crest.svg/100px-AFC_Wimbledon_crest.svg.png',
  'Barrow': 'https://upload.wikimedia.org/wikipedia/en/thumb/9/91/Barrow_A.F.C._logo.svg/100px-Barrow_A.F.C._logo.svg.png',
  'Barrow AFC': 'https://upload.wikimedia.org/wikipedia/en/thumb/9/91/Barrow_A.F.C._logo.svg/100px-Barrow_A.F.C._logo.svg.png',
  'Bradford City': 'https://upload.wikimedia.org/wikipedia/en/thumb/3/32/Bradford_City_AFC_logo.svg/100px-Bradford_City_AFC_logo.svg.png',
  'Bradford City AFC': 'https://upload.wikimedia.org/wikipedia/en/thumb/3/32/Bradford_City_AFC_logo.svg/100px-Bradford_City_AFC_logo.svg.png',
  'Bromley': 'https://upload.wikimedia.org/wikipedia/en/thumb/4/48/Bromley_FC.svg/100px-Bromley_FC.svg.png',
  'Bromley FC': 'https://upload.wikimedia.org/wikipedia/en/thumb/4/48/Bromley_FC.svg/100px-Bromley_FC.svg.png',
  'Carlisle United': 'https://upload.wikimedia.org/wikipedia/en/thumb/f/f9/Carlisle_United_FC_logo.svg/100px-Carlisle_United_FC_logo.svg.png',
  'Carlisle United FC': 'https://upload.wikimedia.org/wikipedia/en/thumb/f/f9/Carlisle_United_FC_logo.svg/100px-Carlisle_United_FC_logo.svg.png',
  'Cheltenham Town': 'https://upload.wikimedia.org/wikipedia/en/thumb/1/17/Cheltenham_Town_FC.svg/100px-Cheltenham_Town_FC.svg.png',
  'Cheltenham Town FC': 'https://upload.wikimedia.org/wikipedia/en/thumb/1/17/Cheltenham_Town_FC.svg/100px-Cheltenham_Town_FC.svg.png',
  'Chesterfield': 'https://upload.wikimedia.org/wikipedia/en/thumb/b/b3/Chesterfield_FC_crest_2016.svg/100px-Chesterfield_FC_crest_2016.svg.png',
  'Chesterfield FC': 'https://upload.wikimedia.org/wikipedia/en/thumb/b/b3/Chesterfield_FC_crest_2016.svg/100px-Chesterfield_FC_crest_2016.svg.png',
  'Colchester United': 'https://upload.wikimedia.org/wikipedia/en/thumb/6/63/Colchester_United_FC_logo.svg/100px-Colchester_United_FC_logo.svg.png',
  'Colchester United FC': 'https://upload.wikimedia.org/wikipedia/en/thumb/6/63/Colchester_United_FC_logo.svg/100px-Colchester_United_FC_logo.svg.png',
  'Crewe Alexandra': 'https://upload.wikimedia.org/wikipedia/en/thumb/8/86/Crewe_Alexandra.svg/100px-Crewe_Alexandra.svg.png',
  'Crewe Alexandra FC': 'https://upload.wikimedia.org/wikipedia/en/thumb/8/86/Crewe_Alexandra.svg/100px-Crewe_Alexandra.svg.png',
  'Doncaster Rovers': 'https://upload.wikimedia.org/wikipedia/en/thumb/4/44/Doncaster_Rovers_F.C._logo.svg/100px-Doncaster_Rovers_F.C._logo.svg.png',
  'Doncaster Rovers FC': 'https://upload.wikimedia.org/wikipedia/en/thumb/4/44/Doncaster_Rovers_F.C._logo.svg/100px-Doncaster_Rovers_F.C._logo.svg.png',
  'Fleetwood Town': 'https://upload.wikimedia.org/wikipedia/en/thumb/7/78/Fleetwood_Town_F.C._logo.svg/100px-Fleetwood_Town_F.C._logo.svg.png',
  'Fleetwood Town FC': 'https://upload.wikimedia.org/wikipedia/en/thumb/7/78/Fleetwood_Town_F.C._logo.svg/100px-Fleetwood_Town_F.C._logo.svg.png',
  'Gillingham': 'https://upload.wikimedia.org/wikipedia/en/thumb/2/2f/Gillingham_FC_logo.svg/100px-Gillingham_FC_logo.svg.png',
  'Gillingham FC': 'https://upload.wikimedia.org/wikipedia/en/thumb/2/2f/Gillingham_FC_logo.svg/100px-Gillingham_FC_logo.svg.png',
  'Grimsby Town': 'https://upload.wikimedia.org/wikipedia/en/thumb/0/07/Grimsby_Town_F.C._logo.svg/100px-Grimsby_Town_F.C._logo.svg.png',
  'Grimsby Town FC': 'https://upload.wikimedia.org/wikipedia/en/thumb/0/07/Grimsby_Town_F.C._logo.svg/100px-Grimsby_Town_F.C._logo.svg.png',
  'Harrogate Town': 'https://upload.wikimedia.org/wikipedia/en/thumb/c/c5/Harrogate_Town_A.F.C._logo.svg/100px-Harrogate_Town_A.F.C._logo.svg.png',
  'Harrogate Town AFC': 'https://upload.wikimedia.org/wikipedia/en/thumb/c/c5/Harrogate_Town_A.F.C._logo.svg/100px-Harrogate_Town_A.F.C._logo.svg.png',
  'Milton Keynes Dons': 'https://upload.wikimedia.org/wikipedia/en/thumb/c/c7/Milton_Keynes_Dons.svg/100px-Milton_Keynes_Dons.svg.png',
  'Milton Keynes Dons FC': 'https://upload.wikimedia.org/wikipedia/en/thumb/c/c7/Milton_Keynes_Dons.svg/100px-Milton_Keynes_Dons.svg.png',
  'Morecambe': 'https://upload.wikimedia.org/wikipedia/en/thumb/0/03/Morecambe_FC.svg/100px-Morecambe_FC.svg.png',
  'Morecambe FC': 'https://upload.wikimedia.org/wikipedia/en/thumb/0/03/Morecambe_FC.svg/100px-Morecambe_FC.svg.png',
  'Newport County': 'https://upload.wikimedia.org/wikipedia/en/thumb/6/65/Newport_County_A.F.C._logo.svg/100px-Newport_County_A.F.C._logo.svg.png',
  'Newport County AFC': 'https://upload.wikimedia.org/wikipedia/en/thumb/6/65/Newport_County_A.F.C._logo.svg/100px-Newport_County_A.F.C._logo.svg.png',
  'Notts County': 'https://upload.wikimedia.org/wikipedia/en/thumb/5/53/Notts_County_FC_logo.svg/100px-Notts_County_FC_logo.svg.png',
  'Notts County FC': 'https://upload.wikimedia.org/wikipedia/en/thumb/5/53/Notts_County_FC_logo.svg/100px-Notts_County_FC_logo.svg.png',
  'Port Vale': 'https://upload.wikimedia.org/wikipedia/en/thumb/9/91/Port_Vale_FC_logo.svg/100px-Port_Vale_FC_logo.svg.png',
  'Port Vale FC': 'https://upload.wikimedia.org/wikipedia/en/thumb/9/91/Port_Vale_FC_logo.svg/100px-Port_Vale_FC_logo.svg.png',
  'Salford City': 'https://upload.wikimedia.org/wikipedia/en/thumb/3/3a/Salford_City_FC_logo.svg/100px-Salford_City_FC_logo.svg.png',
  'Salford City FC': 'https://upload.wikimedia.org/wikipedia/en/thumb/3/3a/Salford_City_FC_logo.svg/100px-Salford_City_FC_logo.svg.png',
  'Sutton United': 'https://upload.wikimedia.org/wikipedia/en/1/17/Sutton_United_FC_logo.png',
  'Sutton United FC': 'https://upload.wikimedia.org/wikipedia/en/1/17/Sutton_United_FC_logo.png',
  'Swindon Town': 'https://upload.wikimedia.org/wikipedia/en/thumb/8/87/Swindon_Town_FC.svg/100px-Swindon_Town_FC.svg.png',
  'Swindon Town FC': 'https://upload.wikimedia.org/wikipedia/en/thumb/8/87/Swindon_Town_FC.svg/100px-Swindon_Town_FC.svg.png',
  'Tranmere Rovers': 'https://upload.wikimedia.org/wikipedia/en/thumb/8/87/Tranmere_Rovers_FC_logo.svg/100px-Tranmere_Rovers_FC_logo.svg.png',
  'Tranmere Rovers FC': 'https://upload.wikimedia.org/wikipedia/en/thumb/8/87/Tranmere_Rovers_FC_logo.svg/100px-Tranmere_Rovers_FC_logo.svg.png',
  'Walsall': 'https://upload.wikimedia.org/wikipedia/en/thumb/e/e3/Walsall_F.C._logo.svg/100px-Walsall_F.C._logo.svg.png',
  'Walsall FC': 'https://upload.wikimedia.org/wikipedia/en/thumb/e/e3/Walsall_F.C._logo.svg/100px-Walsall_F.C._logo.svg.png',

  // National League
  'Fylde': 'https://upload.wikimedia.org/wikipedia/en/thumb/1/12/AFC_Fylde_logo.svg/100px-AFC_Fylde_logo.svg.png',
  'AFC Fylde': 'https://upload.wikimedia.org/wikipedia/en/thumb/1/12/AFC_Fylde_logo.svg/100px-AFC_Fylde_logo.svg.png',
  'Forest Green Rovers': 'https://upload.wikimedia.org/wikipedia/en/thumb/8/89/Forest_Green_Rovers_FC_logo.svg/100px-Forest_Green_Rovers_FC_logo.svg.png',
  'Forest Green Rovers FC': 'https://upload.wikimedia.org/wikipedia/en/thumb/8/89/Forest_Green_Rovers_FC_logo.svg/100px-Forest_Green_Rovers_FC_logo.svg.png',
};
